### ISSUE TITLE
Write locked file calls success handler

### ISSUE THREAD

**Issue by Laoujin** [ljharb/node-json-file#7]
```
jsonFile(packageJsonPath, function (err, file) {
			if (err) {
				console.log('DIRECT CALLBACK', err);
			}
			file.set({
				license: licenseKey
			});

			file.save(function(err) {
				if (err) {
					console.log('direct SAVE error', err);
				}
			}).then(function () {
				console.log('success!');
			}).catch(function (err) {
				console.log('error!', err);
			});
		});
```

This prints "success!" when writing to a file that has a write lock on it.

**Comment by ljharb** [comment]
@Laoujin Thanks for the report! What OS are you running this on? Can you provide more info about how you set up the write lock?

**Comment by ljharb** [comment]
Also, can you do `console.log('success!', arguments)`? I suspect that the promise is getting resolved with an error, by mistake :-)

**Comment by Laoujin** [comment]
Hey ljharb.
This is on Windows 8.1

I locked the file in a PowerShell:
` $file = [System.io.File]::Open('.\package.json', 'Open', 'Read', 'Read')`

The result of logging arguments:
```
 { '0':
   { [Error: EBUSY, open 'C:\code\JavaScript\license-generator\package.json']
     errno: -4082,
     code: 'EBUSY',
     path: 'C:\\code\\JavaScript\\license-generator\\package.json' } }
```

**Comment by ljharb** [comment]
@Laoujin Can you try `npm install`ing from the latest git master, and see if this fixes your issue? You should see a Promise rejected with the EBUSY error (or a callback called with it).

**Comment by Laoujin** [comment]
It now executes the `console.log('direct SAVE error', err);`

With err being:
```
 { [Error: EBUSY, open 'C:\code\test\json-test\package.json']
  errno: -4082,
  code: 'EBUSY',
  path: 'C:\\code\\test\\json-test\\package.json' }
error! { [Error: EBUSY, open 'C:\code\test\json-test\package.json']
  errno: -4082,
  code: 'EBUSY',
  path: 'C:\\code\\test\\json-test\\package.json' }
```

**Comment by ljharb** [comment]
Awesome, that looks like the correct behavior! (both the callback receiving an error, and the `.catch` triggering). I'll publish this today.
